routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use GuzzleHttp\Psr7\Request;

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

Route::get('/coin/{coin_name}','CoinController@show')->name('coin.name');

Route::get('/coin-listing',function (){
    return view('coin-listing');
})->name('coin-listing');


Route::post('/coin-mail','CoinController@coinMail')->name('coin.mail');

Route::middleware(['auth'])->group(function () {

    Route::get('/admin/login', 'Auth\LoginController@login')->name('admin.login');

    Route::get('/home', 'CoinController@index')->name('home');

    Route::resource('coins','CoinController');

    Route::get('/coin/social/{id}','CoinController@social')->name('coin.social');
    Route::post('/coin/social/store','CoinController@social_store')->name('social.store');
    Route::post('/coin/social/update/{id}','CoinController@social_update')->name('social.update');

});


Route::get('/deneme',function (){
/*    $api = new CoingeckoApi();
dd($api->shared()->getExchangeRates());
    $timestamp = $api->shared()->priceCharts(Api::BASE_ETH, Api::QUOTE_USD, Api::PERIOD_24HOURS, true);
    dd($timestamp);*/

//"id": "dash",
//    "symbol": "dash",
//    "name": "Dash"

    $client = new \GuzzleHttp\Client();
    /**
       return coin id,symbol and name
    */
    $response1 = $client->get('https://api.coingecko.com/api/v3/coins/list');

    /**
     * return coin btc price
     */
    $response2 = $client->get('https://api.coingecko.com/api/v3/simple/price?ids=dash&vs_currencies=btc');
    echo "<pre>";
    dd(json_decode((string)$response1->getBody()));

});

resources/views/create_coin.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-8 offset-2">
    @include('layouts.alerts')
    <div class="block rounded">
        <div class="block-header bg-black-op-25">
            <h3 class="block-title text-light">Add New Coin</h3>
        </div>
        <div class="block-content">
            <form action="{!! route('coins.store') !!}" method="post">
                @csrf
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="name">Coin Name</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter Coin Name" value="{{ \Request::old('name') }}" required autocomplete="off">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="ticker">Coin Ticker</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="ticker" name="ticker" placeholder="Enter Coin's Ticker" value="{{ \Request::old('ticker') }}" required autocomplete="off">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="exchange_api_url">Exchange API Url</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="exchange_api_url" name="exchange_api_url" placeholder="Enter Coin's Exchange API Url" value="{{ \Request::old('exchange_api_url') }}" autocomplete="off">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="mn_count_api_url">Masternode Count API Url</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="mn_count_api_url" name="mn_count_api_url" placeholder="Enter Coin's Masternode Count Url" value="{{ \Request::old('mn_count_api_url') }}" autocomplete="off">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="circulation_supply_api_url">Circulation API Url</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="circulation_supply_api_url" name="circulation_supply_api_url" placeholder="Enter Coin's Circulation API Url" value="{{ \Request::old('circulation_supply_api_url') }}" autocomplete="off">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="paid_rewards_mn">Paid Rewards For Masternodes</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="paid_rewards_mn" name="paid_rewards_mn" placeholder="Enter Paid Rewards For Masternodes" value="{{ \Request::old('paid_rewards_mn') }}" autocomplete="off">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="mn_required_coins">MasterNode Required Coins</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="mn_required_coins" name="mn_required_coins" placeholder="MasterNode Required Coins" value="{{ \Request::old('mn_required_coins') }}" autocomplete="off">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="mn_block_reward">MasterNode Block Reward</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="mn_block_reward" name="mn_block_reward" placeholder="MasterNode Required Coins (Enter In Coin Type)" value="{{ \Request::old('mn_block_reward') }}" autocomplete="off">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="icon_url">Icon URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="icon_url" name="icon_url" placeholder="Enter Coin's Icon URL" value="{{ \Request::old('icon_url') }}" required autocomplete="off">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="icon_url">Coin Display Type</label>
                    <div class="col-lg-7">
                        <label class="css-control css-control-success css-radio hide">
                            <input type="radio" class="css-control-input" name="display_type" value="0" {{ \Request::old('display_type') == '0' ? 'checked' : '' }}>
                            <span class="css-control-indicator"></span> NORMAL
                        </label>
                        <label class="css-control css-control-success css-radio hide">
                            <input type="radio" class="css-control-input" name="display_type" value="1" {{ \Request::old('display_type') == '1' ? 'checked' : '' }}>
                            <span class="css-control-indicator"></span> ICO
                        </label>
                        <label class="css-control css-control-success css-radio show">
                            <input type="radio" class="css-control-input" name="display_type" value="2" {{ \Request::old('display_type') == '2' ? 'checked' : '' }}>
                            <span class="css-control-indicator"></span> COMING SOON
                        </label>
                        <label class="css-control css-control-success css-radio show">
                            <input type="radio" class="css-control-input" name="display_type" value="3" {{ \Request::old('display_type') == '3' ? 'checked' : '' }}>
                            <span class="css-control-indicator"></span> MAINTENANCE
                        </label>
                    </div>
                </div>

                <div class="form-group row notes" style="display: none;">
                    <label class="col-lg-4 col-form-label" for="notes">Notes</label>
                    <div class="col-lg-7">
                        <textarea class="form-control" id="notes" name="notes" rows="6" placeholder="Notes.." style="margin-top: 0px; margin-bottom: 0px; height: 137px;">{{ \Request::old('notes') }}</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-lg-9 ml-auto">
                        <a href="{!! route('coins.index') !!}" class="offset-5"> <button class="btn btn-outline-purple"><i class="fas fa-chevron-circle-left"></i> Back</button></a>
                        <button type="submit" class="btn btn-outline-success offset-1"><i class="fas fa-plus-circle"></i> Add</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@push('scripts')
    <script>
        $('.show').on('click',function () {
            $('.notes').removeAttr("style");
        });
        $('.hide').on('click',function () {
            $('.notes').css({'display':'none'});
        })
    </script>
@endpush

resources/views/create_social.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-8 offset-2">
    @include('layouts.alerts')
    <div class="block">
        <div class="block-header bg-black-op-25">
            <h3 class="block-title text-light">Social Media</h3>
        </div>

        <div class="block-content">
            <form action="{!! isset($coin->social) ? route('social.update',$coin->social->id) : route('social.store') !!}" method="post">
                @csrf

                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="website">Website URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="website" name="website" placeholder="Enter Website URL" value="{!! isset($coin->social->website) ? $coin->social->website : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="github">Github URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="github" name="github" placeholder="Enter Github URL" value="{!! isset($coin->social->github) ? $coin->social->github : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="marketcap">Marketcap URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="marketcap" name="marketcap" placeholder="Enter Marketcap URL" value="{!! isset($coin->social->marketcap) ? $coin->social->marketcap : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="explorer">Explorer URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="explorer" name="explorer" placeholder="Enter Explorer URL" value="{!! isset($coin->social->explorer) ? $coin->social->explorer : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="twitter">Twitter URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Enter Twitter URL" value="{!! isset($coin->social->twitter) ? $coin->social->twitter : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="facebook">Facebook URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="facebook" name="facebook" placeholder="Enter Facebook URL" value="{!! isset($coin->social->facebook) ? $coin->social->facebook : null !!}">
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="discord">Discord URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="discord" name="discord" placeholder="Enter Discord URL" value="{!! isset($coin->social->discord) ? $coin->social->discord : null !!}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="reddit">Reddit URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="reddit" name="reddit" placeholder="Enter Reddit URL" value="{!! isset($coin->social->reddit) ? $coin->social->reddit : null !!}">
                    </div>
                </div>

                <input type="hidden" name="coin_name" value="{!! $coin->name !!}">
                <input type="hidden" name="coin_id" value="{!! $coin->id !!}">
                <div class="form-group row">
                    <div class="col-lg-9 ml-auto">
                        <a href="{!! route('coins.index') !!}" class="offset-5"> <button class="btn btn-outline-purple"><i class="fas fa-chevron-circle-left"></i> Back</button></a>
                        <button type="submit" class="btn btn-outline-success offset-1"><i class="fas fa-plus-circle"></i> Add</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



@endsection

resources/views/edit_coin.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-8 offset-2">
    @include('layouts.alerts')
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">Edit {{ $coin->name }}</h3>
        </div>
        <div class="block-content">
            <form action="{!! route('coins.update',$coin->id) !!}" method="post">
                @csrf @method('PUT')
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="name">Coin Name</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter Coin Name" required autocomplete="off" value="{{ $coin->name }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="ticker">Coin Ticker</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="ticker" name="ticker" placeholder="Enter Coin's Ticker" required autocomplete="off" value="{{ $coin->ticker }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="exchange_api_url">Exchange API Url</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="exchange_api_url" name="exchange_api_url" placeholder="Enter Coin's Exchange API Url" required autocomplete="off" value="{{ $coin->exchange_api_url }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="mn_count_api_url">Masternode Count API Url</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="mn_count_api_url" name="mn_count_api_url" placeholder="Enter Coin's Masternode Count Url" required autocomplete="off" value="{{ $coin->mn_count_api_url }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="circulation_supply_api_url">Circulation API Url</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="circulation_supply_api_url" name="circulation_supply_api_url" placeholder="Enter Coin's Circulation API Url" required autocomplete="off" value="{{ $coin->circulation_supply_api_url }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="paid_rewards_mn">Paid Rewards For Masternodes</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="paid_rewards_mn" name="paid_rewards_mn" placeholder="Enter Paid Rewards For Masternodes" required autocomplete="off" value="{{ $coin->paid_rewards_mn }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="mn_required_coins">MasterNode Required Coins</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="mn_required_coins" name="mn_required_coins" placeholder="MasterNode Required Coins" required autocomplete="off" value="{{ $coin->mn_required_coins }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="mn_block_reward">MasterNode Block Reward</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="mn_block_reward" name="mn_block_reward" placeholder="MasterNode Required Coins (Enter In Coin Type)" required autocomplete="off" value="{{ $coin->mn_block_reward }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="icon_url">Icon URL</label>
                    <div class="col-lg-7">
                        <input type="text" class="form-control" id="icon_url" name="icon_url" placeholder="Enter Coin's Icon URL" required autocomplete="off" value="{{ $coin->icon_url }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-lg-4 col-form-label" for="icon_url">Coin Display Type</label>
                    <div class="col-lg-7">
                        <label class="css-control css-control-success css-radio hide">
                            <input type="radio" class="css-control-input" name="display_type" value="0" {{ ($coin->ico == '0' && $coin->maintenance == '0' && $coin->coming_soon == '0' && $coin->simple == '0') ? 'checked' : '' }}>
                            <span class="css-control-indicator"></span> NORMAL
                        </label>
                        <label class="css-control css-control-success css-radio  hide">
                            <input type="radio" class="css-control-input" name="display_type" value="1" {{ $coin->simple == '1' ? 'checked' : '' }}>
                            <span class="css-control-indicator"></span> SIMPLE STATIC
                        </label>
                        <label class="css-control css-control-success css-radio show">
                            <input type="radio" class="css-control-input" name="display_type" value="1" {{ $coin->ico == '1' ? 'checked' : '' }}>
                            <span class="css-control-indicator"></span> ICO
                        </label>
                        <label class="css-control css-control-success css-radio show">
                            <input type="radio" class="css-control-input" name="display_type" value="2" {{ $coin->coming_soon == '1' ? 'checked' : '' }} >
                            <span class="css-control-indicator"></span> COMING SOON
                        </label>
                        <label class="css-control css-control-success css-radio show">
                            <input type="radio" class="css-control-input" name="display_type" value="3" {{ $coin->maintenance == '1' ? 'checked' : '' }}>
                            <span class="css-control-indicator"></span> MAINTENANCE
                        </label>
                    </div>
                </div>

                <div class="form-group row notes" style="display: none;">
                    <label class="col-lg-4 col-form-label" for="notes">Notes</label>
                    <div class="col-lg-7">
                        <textarea class="form-control" id="notes" name="notes" rows="6" placeholder="Notes.." style="margin-top: 0px; margin-bottom: 0px; height: 137px;">{{ isset($coin->notes) ? $coin->notes : '' }}</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-lg-9 ml-auto">
                        <a href="{!! route('coins.index') !!}" class="btn btn-alt-danger offset-5"> Back</a>
                        <button type="submit" class="btn btn-alt-primary offset-1"> Edit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@push('scripts')
    <script>
        $('.show').on('click',function () {
            $('.notes').removeAttr("style");
        });
        $('.hide').on('click',function () {
            $('.notes').css({'display':'none'});
        })
        if ($('.show input')) {
            $('.notes').removeAttr("style");
        }
    </script>
@endpush

resources/views/home.blade.php
@extends('layouts.app')
@push('styles')
    <style>
        a{ color: #7e7ee8 !important }
    </style>
@endpush
@section('content')
    @include('layouts.alerts')
    <div class="row">
        <div class="col-12">
            <a href="{!! route('coins.create') !!}" class="float-right">
                <button class="btn btn-outline-purple"><i class="fa fa-plus-circle"></i> Add New Coin</button>
            </a>
        </div>
    </div>
    <br>
    <div id="DataTables_Table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered table-striped table-vcenter js-dataTable-full dataTable no-footer" id="DataTables_Table_1" role="grid">
                    <thead>
                    <tr role="row">
                        <th class="sorting" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1"
                            colspan="1" aria-label="Name: activate to sort column ascending">Name
                        </th>
                        <th class="d-none d-sm-table-cell sorting" tabindex="0"
                            aria-controls="DataTables_Table_1" rowspan="1" colspan="1">
                            VOLUME
                        </th>
                        <th class="d-none d-sm-table-cell sorting_desc" style="width: 15%;" tabindex="0"
                            aria-controls="DataTables_Table_1" rowspan="1" colspan="1"
                            aria-label="Access: activate to sort column ascending" aria-sort="descending">
                            MARKET CAP
                        </th>
                        <th class="text-center sorting_disabled" style="width: 15%;" rowspan="1" colspan="1"
                            aria-label="Profile">PRICE
                        </th>
                        <th class="text-center sorting_disabled" style="width: 15%;" rowspan="1" colspan="1"
                            aria-label="Profile">CHANGE
                        </th>
                        <th class="text-center sorting_disabled" style="width: 15%;" rowspan="1" colspan="1"
                            aria-label="Profile">ROI
                        </th>
                        <th class="text-center sorting_disabled" style="width: 15%;" rowspan="1" colspan="1"
                            aria-label="Profile">MN WORTH
                        </th>
                        <th class="text-center sorting_disabled" style="width: 15%;" rowspan="1" colspan="1"
                            aria-label="Profile">STATUS
                        </th>
                        <td>
                            Action
                        </td>
                    </tr>
                    </thead>
                    <tbody>
                @if(isset($coins) && count($coins))
                    @foreach($coins as $coin)
                        @php
                            $status = 'NORMAL';
                            if ($coin->ico == '1') {
                                $status = 'ICO';
                            }elseif ($coin->coming_soon == '1') {
                                $status = 'COMING SOON';
                            }elseif ($coin->maintenance == '1') {
                                $status = 'MAINTENANCE';
                            }elseif ($coin->simple == '1') {
                                $status = 'SIMPLE STATICS';
                            }
                        @endphp
                        <tr role="row" class="odd">
                            <td class="text-center"><a href="{!! route('coin.name',$coin->name) !!}" target="_blank"><img src="{!! $coin->icon_url !!}" alt="{!! $coin->name !!}" width="20"> <strong>{!! $coin->name !!}</strong>  </a></td>
                            <td class="font-w600">{!! number_format((float)$usd_24h_vol[$coin->name], 2, '.', ',') !!} $</td>
                            <td class="d-none d-sm-table-cell">{!! number_format((float)$market_cap[$coin->name], 2, '.', ',') !!} $</td>
                            <td class="d-none d-sm-table-cell">{!! $usd[$coin->name] !!} $</td>
                            <td class="d-none d-sm-table-cell"> <span style="color: {!! $usd_24h_change[$coin->name] < 0 ? 'red' : 'green' !!}">% {!! number_format((float)$usd_24h_change[$coin->name], 2, '.', ',') !!} <i class="fa fa-angle-double-{!! $usd_24h_change[$coin->name] < 0 ? 'down' : 'up' !!}"></i> </span></td>
                            <td class="d-none d-sm-table-cell">{!! number_format((float)$roi_percent[$coin->name], 2, '.', ',').'% / '.(int)$roi_days[$coin->name] !!} Days</td>
                            <td class="d-none d-sm-table-cell">{!! number_format((float)$mn_worth[$coin->name], 3, '.', ',') !!} $</td>
                            <td class="d-none d-sm-table-cell">{!! $status !!}</td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <a href="{!! route('coins.edit',$coin->id) !!}" class="btn btn-sm btn-secondary js-tooltip-enabled" data-toggle="tooltip" title="Edit" data-original-title="Edit">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                    <form action="{!! route('coins.destroy',$coin->id) !!}" method="POST">
                                        @csrf @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-secondary js-tooltip-enabled" data-toggle="tooltip" title="Delete" data-original-title="Delete">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </form>
                                    <a href="{!! route('coin.social',$coin->id) !!}" class="btn btn-sm btn-secondary js-tooltip-enabled" data-toggle="tooltip" title="Social Media" data-original-title="Social">
                                        <i class="fa fa-link"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                @endif
          </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection